Error in Square.gds:

Traceback (most recent call last):
  File "/tmp/tmpttp6prt3/temp_script.py", line 17, in <module>
    lib.write_gds('square_design.gds', unit=1.0e-6, precision=1.0e-9)
TypeError: GdsLibrary.write_gds() got an unexpected keyword argument 'unit'
